# Research Question:

How do refugee populations change over time? 

How does the refugee population change in terms of demographics (where are the refugees coming from) and in sheer size? 

Are there differences in time frame? 

Are there certain groups of refugees who make up a larger proportion of total refugees over time?


To look at: 
- track number of refugees in Jordan, Lebanon, and Turkey from 2005 - 2019
  - we want to track from 2005 to witness how the country was dealing with refugees before witnessing a huge influx of individuals and after refugee/asylee numbers rapidly increased
  - these tables will help to identify when major changes in refugee/asylee populations took place in each country, and the extent to which they increased 
- track population make up of refugees over time for each country 

##Data sources:
- [UNHCR Statistics Porta](http://popstats.unhcr.org/en/time_series)l: For the Syrian Statistics Tables for Jordan, Lebanon, and Turkey, data is used from the United Nations High Commissoner for Refugees Statistics Portal time series data. 

- [Financial Tracking Service](https://fts.unocha.org/appeals/724/flows?fts_c=simple_property_4%2Cdirectional_property%2Cdirectional_property_1%2Cdirectional_property_3%2Csimple_property%2Cdirectional_property_2%2Csimple_property_1%2Csimple_property_2%2Csimple_property_3%2Cdirectional_property_4%2Cdirectional_property_8#block-system-main):
This data is used to track funding for the Syrian refugee crisis and funding to meet the requests of the UNHCR for the 3RP ([Syrian Refugee Response and Resiliancy Plan](http://reporting.unhcr.org/sites/default/files/Syria%203RP%20Regional%20Strategic%20Overview%202018-2019%20%28December%202017%29.pdf?v=2)). This specific data set shows funding from various sources, the destination organization, funding amount and status, destination country, and destination crisis.

- [Integrated Nettwork for Societal Conflict Research (INSCR)](http://www.systemicpeace.org/inscrdata.html):  This data is used to observe a time series of "Major Episodes of Political Violence, 1946-2017" with specific focus on the conflict in Syria. This can be used to see how major episodes of political violence correlates with refugee population changes in Jordan, Lebanon, and Turkey.

## Sryian refugees in Jordan, Lebanon, and Turkey

This table represents the population of both refugees and asylum seekers coming from Syria and entering Jordan, Lebanon, and Turkey from 2005 - 2017. 

The data for the following tables was retrieved from the United Nations High Commissioner for Refugees Population Statistics portal [available here](http://popstats.unhcr.org/en/time_series).

*Note: this is the source used for Jordan, Lebanon, and Turkey*

*Another note: in each table, Value = Population size*

In [0]:
import pandas as pd

##Jordan

Syrian Statistics Table for Jordan

In [26]:
samplesyrianpop_jordan = pd.read_excel("syrianpop_jordan.xlsx")
print(samplesyrianpop_jordan)

    Year Country / territory of asylum/residence            Origin  \
0   2005                                  Jordan  Syrian Arab Rep.
1   2005                                  Jordan  Syrian Arab Rep.
2   2006                                  Jordan  Syrian Arab Rep.
3   2006                                  Jordan  Syrian Arab Rep.
4   2007                                  Jordan  Syrian Arab Rep.
5   2007                                  Jordan  Syrian Arab Rep.
6   2008                                  Jordan  Syrian Arab Rep.
7   2008                                  Jordan  Syrian Arab Rep.
8   2009                                  Jordan  Syrian Arab Rep.
9   2009                                  Jordan  Syrian Arab Rep.
10  2010                                  Jordan  Syrian Arab Rep.
11  2010                                  Jordan  Syrian Arab Rep.
12  2011                                  Jordan  Syrian Arab Rep.
13  2011                                  Jordan  Syrian Arab Rep.
14  2012                                  Jordan  Syrian Arab Rep.
15  2012                                  Jordan  Syrian Arab Rep.
16  2013                                  Jordan  Syrian Arab Rep.
17  2014                                  Jordan  Syrian Arab Rep.
18  2015                                  Jordan  Syrian Arab Rep.
19  2016                                  Jordan  Syrian Arab Rep.
20  2017                                  Jordan  Syrian Arab Rep.

                             Population type   Value
0                             Asylum-seekers      65
1   Refugees (incl. refugee-like situations)      40
2                             Asylum-seekers      57
3   Refugees (incl. refugee-like situations)      42
4                             Asylum-seekers      60
5   Refugees (incl. refugee-like situations)      41
6                             Asylum-seekers     124
7   Refugees (incl. refugee-like situations)      44
8                             Asylum-seekers     144
9   Refugees (incl. refugee-like situations)     138
10                            Asylum-seekers     287
11  Refugees (incl. refugee-like situations)     198
12                            Asylum-seekers    2618
13  Refugees (incl. refugee-like situations)     193
14                            Asylum-seekers     491
15  Refugees (incl. refugee-like situations)  238798
16  Refugees (incl. refugee-like situations)  585304
17  Refugees (incl. refugee-like situations)  623112
18  Refugees (incl. refugee-like situations)  628223
19  Refugees (incl. refugee-like situations)  648836
20  Refugees (incl. refugee-like situations)  653031

In [27]:
print(samplesyrianpop_jordan.columns)
print(list(samplesyrianpop_jordan))

Index(['Year', 'Country / territory of asylum/residence', 'Origin',
       'Population type', 'Value'],
      dtype='object')
['Year', 'Country / territory of asylum/residence', 'Origin', 'Population type', 'Value']

###Jordan: 
Modified Syrian Statistics Table- Year,  Population type, Value

In [28]:
jordanstats = samplesyrianpop_jordan[["Year", "Country / territory of asylum/residence", "Population type", "Value"]]
print(jordanstats)

    Year Country / territory of asylum/residence  \
0   2005                                  Jordan
1   2005                                  Jordan
2   2006                                  Jordan
3   2006                                  Jordan
4   2007                                  Jordan
5   2007                                  Jordan
6   2008                                  Jordan
7   2008                                  Jordan
8   2009                                  Jordan
9   2009                                  Jordan
10  2010                                  Jordan
11  2010                                  Jordan
12  2011                                  Jordan
13  2011                                  Jordan
14  2012                                  Jordan
15  2012                                  Jordan
16  2013                                  Jordan
17  2014                                  Jordan
18  2015                                  Jordan
19  2016                                  Jordan
20  2017                                  Jordan

                             Population type   Value
0                             Asylum-seekers      65
1   Refugees (incl. refugee-like situations)      40
2                             Asylum-seekers      57
3   Refugees (incl. refugee-like situations)      42
4                             Asylum-seekers      60
5   Refugees (incl. refugee-like situations)      41
6                             Asylum-seekers     124
7   Refugees (incl. refugee-like situations)      44
8                             Asylum-seekers     144
9   Refugees (incl. refugee-like situations)     138
10                            Asylum-seekers     287
11  Refugees (incl. refugee-like situations)     198
12                            Asylum-seekers    2618
13  Refugees (incl. refugee-like situations)     193
14                            Asylum-seekers     491
15  Refugees (incl. refugee-like situations)  238798
16  Refugees (incl. refugee-like situations)  585304
17  Refugees (incl. refugee-like situations)  623112
18  Refugees (incl. refugee-like situations)  628223
19  Refugees (incl. refugee-like situations)  648836
20  Refugees (incl. refugee-like situations)  653031

In [29]:
jordanstats["year_type"]= jordanstats["Year"].apply(str) + "_" + jordanstats["Population type"]
print(jordanstats)

    Year Country / territory of asylum/residence  \
0   2005                                  Jordan
1   2005                                  Jordan
2   2006                                  Jordan
3   2006                                  Jordan
4   2007                                  Jordan
5   2007                                  Jordan
6   2008                                  Jordan
7   2008                                  Jordan
8   2009                                  Jordan
9   2009                                  Jordan
10  2010                                  Jordan
11  2010                                  Jordan
12  2011                                  Jordan
13  2011                                  Jordan
14  2012                                  Jordan
15  2012                                  Jordan
16  2013                                  Jordan
17  2014                                  Jordan
18  2015                                  Jordan
19  2016                                  Jordan
20  2017                                  Jordan

                             Population type   Value  \
0                             Asylum-seekers      65
1   Refugees (incl. refugee-like situations)      40
2                             Asylum-seekers      57
3   Refugees (incl. refugee-like situations)      42
4                             Asylum-seekers      60
5   Refugees (incl. refugee-like situations)      41
6                             Asylum-seekers     124
7   Refugees (incl. refugee-like situations)      44
8                             Asylum-seekers     144
9   Refugees (incl. refugee-like situations)     138
10                            Asylum-seekers     287
11  Refugees (incl. refugee-like situations)     198
12                            Asylum-seekers    2618
13  Refugees (incl. refugee-like situations)     193
14                            Asylum-seekers     491
15  Refugees (incl. refugee-like situations)  238798
16  Refugees (incl. refugee-like situations)  585304
17  Refugees (incl. refugee-like situations)  623112
18  Refugees (incl. refugee-like situations)  628223
19  Refugees (incl. refugee-like situations)  648836
20  Refugees (incl. refugee-like situations)  653031

                                        year_type
0                             2005_Asylum-seekers
1   2005_Refugees (incl. refugee-like situations)
2                             2006_Asylum-seekers
3   2006_Refugees (incl. refugee-like situations)
4                             2007_Asylum-seekers
5   2007_Refugees (incl. refugee-like situations)
6                             2008_Asylum-seekers
7   2008_Refugees (incl. refugee-like situations)
8                             2009_Asylum-seekers
9   2009_Refugees (incl. refugee-like situations)
10                            2010_Asylum-seekers
11  2010_Refugees (incl. refugee-like situations)
12                            2011_Asylum-seekers
13  2011_Refugees (incl. refugee-like situations)
14                            2012_Asylum-seekers
15  2012_Refugees (incl. refugee-like situations)
16  2013_Refugees (incl. refugee-like situations)
17  2014_Refugees (incl. refugee-like situations)
18  2015_Refugees (incl. refugee-like situations)
19  2016_Refugees (incl. refugee-like situations)
20  2017_Refugees (incl. refugee-like situations)

###Jordan Totals
Combining totals of refugees + asylum seekers for each year.
- Doing this because some years have multiple values; one value for refugees and one value for asylum seekers.

In [30]:
jordantotals = jordanstats.groupby("Year").sum()
print(jordantotals)

       Value
Year
2005     105
2006      99
2007     101
2008     168
2009     282
2010     485
2011    2811
2012  239289
2013  585304
2014  623112
2015  628223
2016  648836
2017  653031

In [31]:
jordantotals["Country"] = "Jordan"
jordantotals["Year"] = jordantotals.index
print(jordantotals)

       Value Country  Year
Year
2005     105  Jordan  2005
2006      99  Jordan  2006
2007     101  Jordan  2007
2008     168  Jordan  2008
2009     282  Jordan  2009
2010     485  Jordan  2010
2011    2811  Jordan  2011
2012  239289  Jordan  2012
2013  585304  Jordan  2013
2014  623112  Jordan  2014
2015  628223  Jordan  2015
2016  648836  Jordan  2016
2017  653031  Jordan  2017

##Lebanon Syrian Statistics
Population of refugees and asylum seekers from Syria per year in Lebanon.

In [32]:
samplesyrianpop_lebanon = pd.read_excel("syrianpop_lebanon.xlsx")
print(samplesyrianpop_lebanon)

    Year Country / territory of asylum/residence            Origin  \
0   2006                                 Lebanon  Syrian Arab Rep.
1   2006                                 Lebanon  Syrian Arab Rep.
2   2007                                 Lebanon  Syrian Arab Rep.
3   2007                                 Lebanon  Syrian Arab Rep.
4   2008                                 Lebanon  Syrian Arab Rep.
5   2008                                 Lebanon  Syrian Arab Rep.
6   2009                                 Lebanon  Syrian Arab Rep.
7   2009                                 Lebanon  Syrian Arab Rep.
8   2010                                 Lebanon  Syrian Arab Rep.
9   2010                                 Lebanon  Syrian Arab Rep.
10  2011                                 Lebanon  Syrian Arab Rep.
11  2011                                 Lebanon  Syrian Arab Rep.
12  2012                                 Lebanon  Syrian Arab Rep.
13  2012                                 Lebanon  Syrian Arab Rep.
14  2013                                 Lebanon  Syrian Arab Rep.
15  2013                                 Lebanon  Syrian Arab Rep.
16  2014                                 Lebanon  Syrian Arab Rep.
17  2014                                 Lebanon  Syrian Arab Rep.
18  2015                                 Lebanon  Syrian Arab Rep.
19  2015                                 Lebanon  Syrian Arab Rep.
20  2016                                 Lebanon  Syrian Arab Rep.
21  2016                                 Lebanon  Syrian Arab Rep.
22  2017                                 Lebanon  Syrian Arab Rep.
23  2017                                 Lebanon  Syrian Arab Rep.

                             Population type    Value
0                             Asylum-seekers       18
1   Refugees (incl. refugee-like situations)        6
2                             Asylum-seekers       42
3   Refugees (incl. refugee-like situations)       48
4                             Asylum-seekers       66
5   Refugees (incl. refugee-like situations)       84
6                             Asylum-seekers      100
7   Refugees (incl. refugee-like situations)       90
8                             Asylum-seekers      141
9   Refugees (incl. refugee-like situations)       64
10                            Asylum-seekers      367
11  Refugees (incl. refugee-like situations)      124
12                            Asylum-seekers      242
13  Refugees (incl. refugee-like situations)   126939
14                            Asylum-seekers      331
15  Refugees (incl. refugee-like situations)   851284
16                            Asylum-seekers      417
17  Refugees (incl. refugee-like situations)  1147494
18                            Asylum-seekers       15
19  Refugees (incl. refugee-like situations)  1062690
20                            Asylum-seekers       10
21  Refugees (incl. refugee-like situations)  1005503
22                            Asylum-seekers        8
23  Refugees (incl. refugee-like situations)   992127

###Lebanon
Modified Syrian Statistics Table: Year, Country, Population Type, Value

In [33]:
lebanonstats = samplesyrianpop_lebanon[["Year", "Country / territory of asylum/residence", "Population type", "Value"]]
print(lebanonstats)

    Year Country / territory of asylum/residence  \
0   2006                                 Lebanon
1   2006                                 Lebanon
2   2007                                 Lebanon
3   2007                                 Lebanon
4   2008                                 Lebanon
5   2008                                 Lebanon
6   2009                                 Lebanon
7   2009                                 Lebanon
8   2010                                 Lebanon
9   2010                                 Lebanon
10  2011                                 Lebanon
11  2011                                 Lebanon
12  2012                                 Lebanon
13  2012                                 Lebanon
14  2013                                 Lebanon
15  2013                                 Lebanon
16  2014                                 Lebanon
17  2014                                 Lebanon
18  2015                                 Lebanon
19  2015                                 Lebanon
20  2016                                 Lebanon
21  2016                                 Lebanon
22  2017                                 Lebanon
23  2017                                 Lebanon

                             Population type    Value
0                             Asylum-seekers       18
1   Refugees (incl. refugee-like situations)        6
2                             Asylum-seekers       42
3   Refugees (incl. refugee-like situations)       48
4                             Asylum-seekers       66
5   Refugees (incl. refugee-like situations)       84
6                             Asylum-seekers      100
7   Refugees (incl. refugee-like situations)       90
8                             Asylum-seekers      141
9   Refugees (incl. refugee-like situations)       64
10                            Asylum-seekers      367
11  Refugees (incl. refugee-like situations)      124
12                            Asylum-seekers      242
13  Refugees (incl. refugee-like situations)   126939
14                            Asylum-seekers      331
15  Refugees (incl. refugee-like situations)   851284
16                            Asylum-seekers      417
17  Refugees (incl. refugee-like situations)  1147494
18                            Asylum-seekers       15
19  Refugees (incl. refugee-like situations)  1062690
20                            Asylum-seekers       10
21  Refugees (incl. refugee-like situations)  1005503
22                            Asylum-seekers        8
23  Refugees (incl. refugee-like situations)   992127

In [34]:
lebanonstats["year_type"]= lebanonstats["Year"].apply(str) + "_" + lebanonstats["Population type"]
print(lebanonstats)

    Year Country / territory of asylum/residence  \
0   2006                                 Lebanon
1   2006                                 Lebanon
2   2007                                 Lebanon
3   2007                                 Lebanon
4   2008                                 Lebanon
5   2008                                 Lebanon
6   2009                                 Lebanon
7   2009                                 Lebanon
8   2010                                 Lebanon
9   2010                                 Lebanon
10  2011                                 Lebanon
11  2011                                 Lebanon
12  2012                                 Lebanon
13  2012                                 Lebanon
14  2013                                 Lebanon
15  2013                                 Lebanon
16  2014                                 Lebanon
17  2014                                 Lebanon
18  2015                                 Lebanon
19  2015                                 Lebanon
20  2016                                 Lebanon
21  2016                                 Lebanon
22  2017                                 Lebanon
23  2017                                 Lebanon

                             Population type    Value  \
0                             Asylum-seekers       18
1   Refugees (incl. refugee-like situations)        6
2                             Asylum-seekers       42
3   Refugees (incl. refugee-like situations)       48
4                             Asylum-seekers       66
5   Refugees (incl. refugee-like situations)       84
6                             Asylum-seekers      100
7   Refugees (incl. refugee-like situations)       90
8                             Asylum-seekers      141
9   Refugees (incl. refugee-like situations)       64
10                            Asylum-seekers      367
11  Refugees (incl. refugee-like situations)      124
12                            Asylum-seekers      242
13  Refugees (incl. refugee-like situations)   126939
14                            Asylum-seekers      331
15  Refugees (incl. refugee-like situations)   851284
16                            Asylum-seekers      417
17  Refugees (incl. refugee-like situations)  1147494
18                            Asylum-seekers       15
19  Refugees (incl. refugee-like situations)  1062690
20                            Asylum-seekers       10
21  Refugees (incl. refugee-like situations)  1005503
22                            Asylum-seekers        8
23  Refugees (incl. refugee-like situations)   992127

                                        year_type
0                             2006_Asylum-seekers
1   2006_Refugees (incl. refugee-like situations)
2                             2007_Asylum-seekers
3   2007_Refugees (incl. refugee-like situations)
4                             2008_Asylum-seekers
5   2008_Refugees (incl. refugee-like situations)
6                             2009_Asylum-seekers
7   2009_Refugees (incl. refugee-like situations)
8                             2010_Asylum-seekers
9   2010_Refugees (incl. refugee-like situations)
10                            2011_Asylum-seekers
11  2011_Refugees (incl. refugee-like situations)
12                            2012_Asylum-seekers
13  2012_Refugees (incl. refugee-like situations)
14                            2013_Asylum-seekers
15  2013_Refugees (incl. refugee-like situations)
16                            2014_Asylum-seekers
17  2014_Refugees (incl. refugee-like situations)
18                            2015_Asylum-seekers
19  2015_Refugees (incl. refugee-like situations)
20                            2016_Asylum-seekers
21  2016_Refugees (incl. refugee-like situations)
22                            2017_Asylum-seekers
23  2017_Refugees (incl. refugee-like situations)

###Lebanon Totals
Combined totals per year of refugees and asylum seekers.

In [35]:
lebanontotals = lebanonstats.groupby("Year").sum()
print(lebanontotals)

lebanontotals["Country"] = "Lebanon"
lebanontotals["Year"] = lebanontotals.index
print(lebanontotals)

        Value
Year
2006       24
2007       90
2008      150
2009      190
2010      205
2011      491
2012   127181
2013   851615
2014  1147911
2015  1062705
2016  1005513
2017   992135
        Value  Country  Year
Year
2006       24  Lebanon  2006
2007       90  Lebanon  2007
2008      150  Lebanon  2008
2009      190  Lebanon  2009
2010      205  Lebanon  2010
2011      491  Lebanon  2011
2012   127181  Lebanon  2012
2013   851615  Lebanon  2013
2014  1147911  Lebanon  2014
2015  1062705  Lebanon  2015
2016  1005513  Lebanon  2016
2017   992135  Lebanon  2017

###Combining Jordan and Lebanon Syrian Statistics Tables.

In [36]:
syrians_jd_lb = jordanstats.merge(lebanonstats, on="year_type", how="outer")
print(syrians_jd_lb)

    Year_x Country / territory of asylum/residence_x  \
0   2005.0                                    Jordan
1   2005.0                                    Jordan
2   2006.0                                    Jordan
3   2006.0                                    Jordan
4   2007.0                                    Jordan
5   2007.0                                    Jordan
6   2008.0                                    Jordan
7   2008.0                                    Jordan
8   2009.0                                    Jordan
9   2009.0                                    Jordan
10  2010.0                                    Jordan
11  2010.0                                    Jordan
12  2011.0                                    Jordan
13  2011.0                                    Jordan
14  2012.0                                    Jordan
15  2012.0                                    Jordan
16  2013.0                                    Jordan
17  2014.0                                    Jordan
18  2015.0                                    Jordan
19  2016.0                                    Jordan
20  2017.0                                    Jordan
21     NaN                                       NaN
22     NaN                                       NaN
23     NaN                                       NaN
24     NaN                                       NaN
25     NaN                                       NaN

                           Population type_x   Value_x  \
0                             Asylum-seekers      65.0
1   Refugees (incl. refugee-like situations)      40.0
2                             Asylum-seekers      57.0
3   Refugees (incl. refugee-like situations)      42.0
4                             Asylum-seekers      60.0
5   Refugees (incl. refugee-like situations)      41.0
6                             Asylum-seekers     124.0
7   Refugees (incl. refugee-like situations)      44.0
8                             Asylum-seekers     144.0
9   Refugees (incl. refugee-like situations)     138.0
10                            Asylum-seekers     287.0
11  Refugees (incl. refugee-like situations)     198.0
12                            Asylum-seekers    2618.0
13  Refugees (incl. refugee-like situations)     193.0
14                            Asylum-seekers     491.0
15  Refugees (incl. refugee-like situations)  238798.0
16  Refugees (incl. refugee-like situations)  585304.0
17  Refugees (incl. refugee-like situations)  623112.0
18  Refugees (incl. refugee-like situations)  628223.0
19  Refugees (incl. refugee-like situations)  648836.0
20  Refugees (incl. refugee-like situations)  653031.0
21                                       NaN       NaN
22                                       NaN       NaN
23                                       NaN       NaN
24                                       NaN       NaN
25                                       NaN       NaN

                                        year_type  Year_y  \
0                             2005_Asylum-seekers     NaN
1   2005_Refugees (incl. refugee-like situations)     NaN
2                             2006_Asylum-seekers  2006.0
3   2006_Refugees (incl. refugee-like situations)  2006.0
4                             2007_Asylum-seekers  2007.0
5   2007_Refugees (incl. refugee-like situations)  2007.0
6                             2008_Asylum-seekers  2008.0
7   2008_Refugees (incl. refugee-like situations)  2008.0
8                             2009_Asylum-seekers  2009.0
9   2009_Refugees (incl. refugee-like situations)  2009.0
10                            2010_Asylum-seekers  2010.0
11  2010_Refugees (incl. refugee-like situations)  2010.0
12                            2011_Asylum-seekers  2011.0
13  2011_Refugees (incl. refugee-like situations)  2011.0
14                            2012_Asylum-seekers  2012.0
15  2012_Refugees (incl. refugee-like situations)  2012.0
16  2013_Refugees (incl. refugee-like situations)  2013.0
17  2014_Refugees (incl. refugee-like situations)  2014.0
18  2015_Refugees (incl. refugee-like situations)  2015.0
19  2016_Refugees (incl. refugee-like situations)  2016.0
20  2017_Refugees (incl. refugee-like situations)  2017.0
21                            2013_Asylum-seekers  2013.0
22                            2014_Asylum-seekers  2014.0
23                            2015_Asylum-seekers  2015.0
24                            2016_Asylum-seekers  2016.0
25                            2017_Asylum-seekers  2017.0

   Country / territory of asylum/residence_y  \
0                                        NaN
1                                        NaN
2                                    Lebanon
3                                    Lebanon
4                                    Lebanon
5                                    Lebanon
6                                    Lebanon
7                                    Lebanon
8                                    Lebanon
9                                    Lebanon
10                                   Lebanon
11                                   Lebanon
12                                   Lebanon
13                                   Lebanon
14                                   Lebanon
15                                   Lebanon
16                                   Lebanon
17                                   Lebanon
18                                   Lebanon
19                                   Lebanon
20                                   Lebanon
21                                   Lebanon
22                                   Lebanon
23                                   Lebanon
24                                   Lebanon
25                                   Lebanon

                           Population type_y    Value_y
0                                        NaN        NaN
1                                        NaN        NaN
2                             Asylum-seekers       18.0
3   Refugees (incl. refugee-like situations)        6.0
4                             Asylum-seekers       42.0
5   Refugees (incl. refugee-like situations)       48.0
6                             Asylum-seekers       66.0
7   Refugees (incl. refugee-like situations)       84.0
8                             Asylum-seekers      100.0
9   Refugees (incl. refugee-like situations)       90.0
10                            Asylum-seekers      141.0
11  Refugees (incl. refugee-like situations)       64.0
12                            Asylum-seekers      367.0
13  Refugees (incl. refugee-like situations)      124.0
14                            Asylum-seekers      242.0
15  Refugees (incl. refugee-like situations)   126939.0
16  Refugees (incl. refugee-like situations)   851284.0
17  Refugees (incl. refugee-like situations)  1147494.0
18  Refugees (incl. refugee-like situations)  1062690.0
19  Refugees (incl. refugee-like situations)  1005503.0
20  Refugees (incl. refugee-like situations)   992127.0
21                            Asylum-seekers      331.0
22                            Asylum-seekers      417.0
23                            Asylum-seekers       15.0
24                            Asylum-seekers       10.0
25                            Asylum-seekers        8.0

###Combining Jordan and Lebanon totals tables:

In [37]:
totals_jd_lb = jordantotals.merge(lebanontotals, on="Year", how="outer")
print(totals_jd_lb)

    Value_x Country_x  Year    Value_y Country_y
0       105    Jordan  2005        NaN       NaN
1        99    Jordan  2006       24.0   Lebanon
2       101    Jordan  2007       90.0   Lebanon
3       168    Jordan  2008      150.0   Lebanon
4       282    Jordan  2009      190.0   Lebanon
5       485    Jordan  2010      205.0   Lebanon
6      2811    Jordan  2011      491.0   Lebanon
7    239289    Jordan  2012   127181.0   Lebanon
8    585304    Jordan  2013   851615.0   Lebanon
9    623112    Jordan  2014  1147911.0   Lebanon
10   628223    Jordan  2015  1062705.0   Lebanon
11   648836    Jordan  2016  1005513.0   Lebanon
12   653031    Jordan  2017   992135.0   Lebanon

##Turkey
Syrian Statistics table for Turkey

In [38]:
samplesyrianpop_turkey = pd.read_excel("syrianpop_turkey.xlsx")
print(samplesyrianpop_turkey)

    Year Country / territory of asylum/residence            Origin  \
0   2005                                  Turkey  Syrian Arab Rep.
1   2005                                  Turkey  Syrian Arab Rep.
2   2006                                  Turkey  Syrian Arab Rep.
3   2006                                  Turkey  Syrian Arab Rep.
4   2007                                  Turkey  Syrian Arab Rep.
5   2007                                  Turkey  Syrian Arab Rep.
6   2008                                  Turkey  Syrian Arab Rep.
7   2008                                  Turkey  Syrian Arab Rep.
8   2009                                  Turkey  Syrian Arab Rep.
9   2009                                  Turkey  Syrian Arab Rep.
10  2010                                  Turkey  Syrian Arab Rep.
11  2010                                  Turkey  Syrian Arab Rep.
12  2011                                  Turkey  Syrian Arab Rep.
13  2011                                  Turkey  Syrian Arab Rep.
14  2012                                  Turkey  Syrian Arab Rep.
15  2012                                  Turkey  Syrian Arab Rep.
16  2013                                  Turkey  Syrian Arab Rep.
17  2013                                  Turkey  Syrian Arab Rep.
18  2014                                  Turkey  Syrian Arab Rep.
19  2014                                  Turkey  Syrian Arab Rep.
20  2015                                  Turkey  Syrian Arab Rep.
21  2015                                  Turkey  Syrian Arab Rep.
22  2016                                  Turkey  Syrian Arab Rep.
23  2016                                  Turkey  Syrian Arab Rep.
24  2017                                  Turkey  Syrian Arab Rep.
25  2017                                  Turkey  Syrian Arab Rep.

                             Population type    Value
0                             Asylum-seekers        7
1   Refugees (incl. refugee-like situations)       12
2                             Asylum-seekers        5
3   Refugees (incl. refugee-like situations)        2
4                             Asylum-seekers       19
5   Refugees (incl. refugee-like situations)        5
6                             Asylum-seekers       21
7   Refugees (incl. refugee-like situations)       12
8                             Asylum-seekers       56
9   Refugees (incl. refugee-like situations)        8
10                            Asylum-seekers       65
11  Refugees (incl. refugee-like situations)        9
12                            Asylum-seekers      205
13  Refugees (incl. refugee-like situations)       19
14                            Asylum-seekers      200
15  Refugees (incl. refugee-like situations)   248466
16                            Asylum-seekers      110
17  Refugees (incl. refugee-like situations)   585601
18                            Asylum-seekers      250
19  Refugees (incl. refugee-like situations)  1557899
20                            Asylum-seekers      297
21  Refugees (incl. refugee-like situations)  2503549
22                            Asylum-seekers      180
23  Refugees (incl. refugee-like situations)  2823987
24                            Asylum-seekers      163
25  Refugees (incl. refugee-like situations)  3424237

###Turkey
Modified Syrian Statistics Table - Year, Country, Population type, Value

In [39]:
turkeystats = samplesyrianpop_turkey[["Year", "Country / territory of asylum/residence", "Population type", "Value"]]
print(turkeystats)

    Year Country / territory of asylum/residence  \
0   2005                                  Turkey
1   2005                                  Turkey
2   2006                                  Turkey
3   2006                                  Turkey
4   2007                                  Turkey
5   2007                                  Turkey
6   2008                                  Turkey
7   2008                                  Turkey
8   2009                                  Turkey
9   2009                                  Turkey
10  2010                                  Turkey
11  2010                                  Turkey
12  2011                                  Turkey
13  2011                                  Turkey
14  2012                                  Turkey
15  2012                                  Turkey
16  2013                                  Turkey
17  2013                                  Turkey
18  2014                                  Turkey
19  2014                                  Turkey
20  2015                                  Turkey
21  2015                                  Turkey
22  2016                                  Turkey
23  2016                                  Turkey
24  2017                                  Turkey
25  2017                                  Turkey

                             Population type    Value
0                             Asylum-seekers        7
1   Refugees (incl. refugee-like situations)       12
2                             Asylum-seekers        5
3   Refugees (incl. refugee-like situations)        2
4                             Asylum-seekers       19
5   Refugees (incl. refugee-like situations)        5
6                             Asylum-seekers       21
7   Refugees (incl. refugee-like situations)       12
8                             Asylum-seekers       56
9   Refugees (incl. refugee-like situations)        8
10                            Asylum-seekers       65
11  Refugees (incl. refugee-like situations)        9
12                            Asylum-seekers      205
13  Refugees (incl. refugee-like situations)       19
14                            Asylum-seekers      200
15  Refugees (incl. refugee-like situations)   248466
16                            Asylum-seekers      110
17  Refugees (incl. refugee-like situations)   585601
18                            Asylum-seekers      250
19  Refugees (incl. refugee-like situations)  1557899
20                            Asylum-seekers      297
21  Refugees (incl. refugee-like situations)  2503549
22                            Asylum-seekers      180
23  Refugees (incl. refugee-like situations)  2823987
24                            Asylum-seekers      163
25  Refugees (incl. refugee-like situations)  3424237

In [40]:
turkeystats["year_type"]= turkeystats["Year"].apply(str) + "_" + turkeystats["Population type"]
print(turkeystats)

    Year Country / territory of asylum/residence  \
0   2005                                  Turkey
1   2005                                  Turkey
2   2006                                  Turkey
3   2006                                  Turkey
4   2007                                  Turkey
5   2007                                  Turkey
6   2008                                  Turkey
7   2008                                  Turkey
8   2009                                  Turkey
9   2009                                  Turkey
10  2010                                  Turkey
11  2010                                  Turkey
12  2011                                  Turkey
13  2011                                  Turkey
14  2012                                  Turkey
15  2012                                  Turkey
16  2013                                  Turkey
17  2013                                  Turkey
18  2014                                  Turkey
19  2014                                  Turkey
20  2015                                  Turkey
21  2015                                  Turkey
22  2016                                  Turkey
23  2016                                  Turkey
24  2017                                  Turkey
25  2017                                  Turkey

                             Population type    Value  \
0                             Asylum-seekers        7
1   Refugees (incl. refugee-like situations)       12
2                             Asylum-seekers        5
3   Refugees (incl. refugee-like situations)        2
4                             Asylum-seekers       19
5   Refugees (incl. refugee-like situations)        5
6                             Asylum-seekers       21
7   Refugees (incl. refugee-like situations)       12
8                             Asylum-seekers       56
9   Refugees (incl. refugee-like situations)        8
10                            Asylum-seekers       65
11  Refugees (incl. refugee-like situations)        9
12                            Asylum-seekers      205
13  Refugees (incl. refugee-like situations)       19
14                            Asylum-seekers      200
15  Refugees (incl. refugee-like situations)   248466
16                            Asylum-seekers      110
17  Refugees (incl. refugee-like situations)   585601
18                            Asylum-seekers      250
19  Refugees (incl. refugee-like situations)  1557899
20                            Asylum-seekers      297
21  Refugees (incl. refugee-like situations)  2503549
22                            Asylum-seekers      180
23  Refugees (incl. refugee-like situations)  2823987
24                            Asylum-seekers      163
25  Refugees (incl. refugee-like situations)  3424237

                                        year_type
0                             2005_Asylum-seekers
1   2005_Refugees (incl. refugee-like situations)
2                             2006_Asylum-seekers
3   2006_Refugees (incl. refugee-like situations)
4                             2007_Asylum-seekers
5   2007_Refugees (incl. refugee-like situations)
6                             2008_Asylum-seekers
7   2008_Refugees (incl. refugee-like situations)
8                             2009_Asylum-seekers
9   2009_Refugees (incl. refugee-like situations)
10                            2010_Asylum-seekers
11  2010_Refugees (incl. refugee-like situations)
12                            2011_Asylum-seekers
13  2011_Refugees (incl. refugee-like situations)
14                            2012_Asylum-seekers
15  2012_Refugees (incl. refugee-like situations)
16                            2013_Asylum-seekers
17  2013_Refugees (incl. refugee-like situations)
18                            2014_Asylum-seekers
19  2014_Refugees (incl. refugee-like situations)
20                            2015_Asylum-seekers
21  2015_Refugees (incl. refugee-like situations)
22                            2016_Asylum-seekers
23  2016_Refugees (incl. refugee-like situations)
24                            2017_Asylum-seekers
25  2017_Refugees (incl. refugee-like situations)

###Turkey Totals
Combined totals for asylum seekers and refugees from Syria in Turkey per year.

In [41]:
turkeytotals = turkeystats.groupby("Year").sum()
print(turkeytotals)

turkeytotals["Country"] = "Turkey"
turkeytotals["Year"] = turkeytotals.index
print(turkeytotals)

        Value
Year
2005       19
2006        7
2007       24
2008       33
2009       64
2010       74
2011      224
2012   248666
2013   585711
2014  1558149
2015  2503846
2016  2824167
2017  3424400
        Value Country  Year
Year
2005       19  Turkey  2005
2006        7  Turkey  2006
2007       24  Turkey  2007
2008       33  Turkey  2008
2009       64  Turkey  2009
2010       74  Turkey  2010
2011      224  Turkey  2011
2012   248666  Turkey  2012
2013   585711  Turkey  2013
2014  1558149  Turkey  2014
2015  2503846  Turkey  2015
2016  2824167  Turkey  2016
2017  3424400  Turkey  2017

##Final Syrian Statistics Table:

Merging Syrian Statistics table of Jordan and Lebanon (already merged) with Turkey:

In [42]:
syrians_jd_lb_tk = syrians_jd_lb.merge(turkeystats, on="year_type", how="outer")
print(syrians_jd_lb_tk)

    Year_x Country / territory of asylum/residence_x  \
0   2005.0                                    Jordan
1   2005.0                                    Jordan
2   2006.0                                    Jordan
3   2006.0                                    Jordan
4   2007.0                                    Jordan
5   2007.0                                    Jordan
6   2008.0                                    Jordan
7   2008.0                                    Jordan
8   2009.0                                    Jordan
9   2009.0                                    Jordan
10  2010.0                                    Jordan
11  2010.0                                    Jordan
12  2011.0                                    Jordan
13  2011.0                                    Jordan
14  2012.0                                    Jordan
15  2012.0                                    Jordan
16  2013.0                                    Jordan
17  2014.0                                    Jordan
18  2015.0                                    Jordan
19  2016.0                                    Jordan
20  2017.0                                    Jordan
21     NaN                                       NaN
22     NaN                                       NaN
23     NaN                                       NaN
24     NaN                                       NaN
25     NaN                                       NaN

                           Population type_x   Value_x  \
0                             Asylum-seekers      65.0
1   Refugees (incl. refugee-like situations)      40.0
2                             Asylum-seekers      57.0
3   Refugees (incl. refugee-like situations)      42.0
4                             Asylum-seekers      60.0
5   Refugees (incl. refugee-like situations)      41.0
6                             Asylum-seekers     124.0
7   Refugees (incl. refugee-like situations)      44.0
8                             Asylum-seekers     144.0
9   Refugees (incl. refugee-like situations)     138.0
10                            Asylum-seekers     287.0
11  Refugees (incl. refugee-like situations)     198.0
12                            Asylum-seekers    2618.0
13  Refugees (incl. refugee-like situations)     193.0
14                            Asylum-seekers     491.0
15  Refugees (incl. refugee-like situations)  238798.0
16  Refugees (incl. refugee-like situations)  585304.0
17  Refugees (incl. refugee-like situations)  623112.0
18  Refugees (incl. refugee-like situations)  628223.0
19  Refugees (incl. refugee-like situations)  648836.0
20  Refugees (incl. refugee-like situations)  653031.0
21                                       NaN       NaN
22                                       NaN       NaN
23                                       NaN       NaN
24                                       NaN       NaN
25                                       NaN       NaN

                                        year_type  Year_y  \
0                             2005_Asylum-seekers     NaN
1   2005_Refugees (incl. refugee-like situations)     NaN
2                             2006_Asylum-seekers  2006.0
3   2006_Refugees (incl. refugee-like situations)  2006.0
4                             2007_Asylum-seekers  2007.0
5   2007_Refugees (incl. refugee-like situations)  2007.0
6                             2008_Asylum-seekers  2008.0
7   2008_Refugees (incl. refugee-like situations)  2008.0
8                             2009_Asylum-seekers  2009.0
9   2009_Refugees (incl. refugee-like situations)  2009.0
10                            2010_Asylum-seekers  2010.0
11  2010_Refugees (incl. refugee-like situations)  2010.0
12                            2011_Asylum-seekers  2011.0
13  2011_Refugees (incl. refugee-like situations)  2011.0
14                            2012_Asylum-seekers  2012.0
15  2012_Refugees (incl. refugee-like situations)  2012.0
16  2013_Refugees (incl. refugee-like situations)  2013.0
17  2014_Refugees (incl. refugee-like situations)  2014.0
18  2015_Refugees (incl. refugee-like situations)  2015.0
19  2016_Refugees (incl. refugee-like situations)  2016.0
20  2017_Refugees (incl. refugee-like situations)  2017.0
21                            2013_Asylum-seekers  2013.0
22                            2014_Asylum-seekers  2014.0
23                            2015_Asylum-seekers  2015.0
24                            2016_Asylum-seekers  2016.0
25                            2017_Asylum-seekers  2017.0

   Country / territory of asylum/residence_y  \
0                                        NaN
1                                        NaN
2                                    Lebanon
3                                    Lebanon
4                                    Lebanon
5                                    Lebanon
6                                    Lebanon
7                                    Lebanon
8                                    Lebanon
9                                    Lebanon
10                                   Lebanon
11                                   Lebanon
12                                   Lebanon
13                                   Lebanon
14                                   Lebanon
15                                   Lebanon
16                                   Lebanon
17                                   Lebanon
18                                   Lebanon
19                                   Lebanon
20                                   Lebanon
21                                   Lebanon
22                                   Lebanon
23                                   Lebanon
24                                   Lebanon
25                                   Lebanon

                           Population type_y    Value_y  Year  \
0                                        NaN        NaN  2005
1                                        NaN        NaN  2005
2                             Asylum-seekers       18.0  2006
3   Refugees (incl. refugee-like situations)        6.0  2006
4                             Asylum-seekers       42.0  2007
5   Refugees (incl. refugee-like situations)       48.0  2007
6                             Asylum-seekers       66.0  2008
7   Refugees (incl. refugee-like situations)       84.0  2008
8                             Asylum-seekers      100.0  2009
9   Refugees (incl. refugee-like situations)       90.0  2009
10                            Asylum-seekers      141.0  2010
11  Refugees (incl. refugee-like situations)       64.0  2010
12                            Asylum-seekers      367.0  2011
13  Refugees (incl. refugee-like situations)      124.0  2011
14                            Asylum-seekers      242.0  2012
15  Refugees (incl. refugee-like situations)   126939.0  2012
16  Refugees (incl. refugee-like situations)   851284.0  2013
17  Refugees (incl. refugee-like situations)  1147494.0  2014
18  Refugees (incl. refugee-like situations)  1062690.0  2015
19  Refugees (incl. refugee-like situations)  1005503.0  2016
20  Refugees (incl. refugee-like situations)   992127.0  2017
21                            Asylum-seekers      331.0  2013
22                            Asylum-seekers      417.0  2014
23                            Asylum-seekers       15.0  2015
24                            Asylum-seekers       10.0  2016
25                            Asylum-seekers        8.0  2017

   Country / territory of asylum/residence  \
0                                   Turkey
1                                   Turkey
2                                   Turkey
3                                   Turkey
4                                   Turkey
5                                   Turkey
6                                   Turkey
7                                   Turkey
8                                   Turkey
9                                   Turkey
10                                  Turkey
11                                  Turkey
12                                  Turkey
13                                  Turkey
14                                  Turkey
15                                  Turkey
16                                  Turkey
17                                  Turkey
18                                  Turkey
19                                  Turkey
20                                  Turkey
21                                  Turkey
22                                  Turkey
23                                  Turkey
24                                  Turkey
25                                  Turkey

                             Population type    Value
0                             Asylum-seekers        7
1   Refugees (incl. refugee-like situations)       12
2                             Asylum-seekers        5
3   Refugees (incl. refugee-like situations)        2
4                             Asylum-seekers       19
5   Refugees (incl. refugee-like situations)        5
6                             Asylum-seekers       21
7   Refugees (incl. refugee-like situations)       12
8                             Asylum-seekers       56
9   Refugees (incl. refugee-like situations)        8
10                            Asylum-seekers       65
11  Refugees (incl. refugee-like situations)        9
12                            Asylum-seekers      205
13  Refugees (incl. refugee-like situations)       19
14                            Asylum-seekers      200
15  Refugees (incl. refugee-like situations)   248466
16  Refugees (incl. refugee-like situations)   585601
17  Refugees (incl. refugee-like situations)  1557899
18  Refugees (incl. refugee-like situations)  2503549
19  Refugees (incl. refugee-like situations)  2823987
20  Refugees (incl. refugee-like situations)  3424237
21                            Asylum-seekers      110
22                            Asylum-seekers      250
23                            Asylum-seekers      297
24                            Asylum-seekers      180
25                            Asylum-seekers      163

##Final Syrian Totals Table

Merging totals refugees + asylum seekers per year for Jordan, Lebanon (already merged), and Turkey:

In [43]:
totals_jd_lb_tk = turkeytotals.merge(totals_jd_lb, on="Year", how="outer")
print(totals_jd_lb_tk)

      Value Country  Year  Value_x Country_x    Value_y Country_y
0        19  Turkey  2005      105    Jordan        NaN       NaN
1         7  Turkey  2006       99    Jordan       24.0   Lebanon
2        24  Turkey  2007      101    Jordan       90.0   Lebanon
3        33  Turkey  2008      168    Jordan      150.0   Lebanon
4        64  Turkey  2009      282    Jordan      190.0   Lebanon
5        74  Turkey  2010      485    Jordan      205.0   Lebanon
6       224  Turkey  2011     2811    Jordan      491.0   Lebanon
7    248666  Turkey  2012   239289    Jordan   127181.0   Lebanon
8    585711  Turkey  2013   585304    Jordan   851615.0   Lebanon
9   1558149  Turkey  2014   623112    Jordan  1147911.0   Lebanon
10  2503846  Turkey  2015   628223    Jordan  1062705.0   Lebanon
11  2824167  Turkey  2016   648836    Jordan  1005513.0   Lebanon
12  3424400  Turkey  2017   653031    Jordan   992135.0   Lebanon

In [0]:
#jordantestsample = pd.read_excel("UNHCR_popstats_jordan.xlsx", skiprows=3)
#print(jordantestsample)

In [45]:
fundingsample = pd.read_excel("ftsdata.xlsx", skiprows=2)
print(fundingsample)

    Flow ID                                        Source org.  \
0    139197                             Germany, Government of
1    154691                      United Kingdom, Government of
2    154692                      United Kingdom, Government of
3    160908                              Canada, Government of
4    160910                              Canada, Government of
5    160911                              Canada, Government of
6    160912                              Canada, Government of
7    161755  European Commission's Humanitarian Aid and Civ...
8    161793                           Australia, Government of
9    171400                               Qatar, Government of
10   177591                           Australia, Government of
11   177613                         Switzerland, Government of
12   179529                         Netherlands, Government of
13   179668                              Canada, Government of
14   187951                              Sweden, Government of
15   188101                   UNICEF National Committee/France
16   188102                             Germany, Government of
17   188103                                                NaN
18   188109                             Germany, Government of
19   188110                             Germany, Government of
20   188111              UNICEF National Committee/Netherlands
21   188112                                 US Fund for UNICEF
22   188113                                 US Fund for UNICEF
23   188139              Private (individuals & organizations)
24   188322            United States of America, Government of
25   188344            United States of America, Government of
26   188348              Private (individuals & organizations)
27   188349                               Japan, Government of
28   188350              Private (individuals & organizations)
29   188351  European Commission's Humanitarian Aid and Civ...
30   188402                              Monaco, Government of
31   188405              Private (individuals & organizations)
32   188406              Private (individuals & organizations)
33   188410                               Japan, Government of
34   188759                             Denmark, Government of
35   189156                               Japan, Government of
36   189162                         Switzerland, Government of
37   189240                             Ireland, Government of

                                     Destination org.        Project code  \
0                      United Nations Children's Fund  RSYR19-MS-157616-1
1                      United Nations Children's Fund  RSYR19-MS-157616-1
2                      United Nations Children's Fund  RSYR19-MS-157616-1
3                      United Nations Children's Fund  RSYR19-MS-157615-1
4                      United Nations Children's Fund  RSYR19-MS-157615-1
5                      United Nations Children's Fund  RSYR19-MS-157616-1
6                      United Nations Children's Fund  RSYR19-MS-157616-1
7       United Nations High Commissioner for Refugees  RSYR19-MS-157634-1
8                      United Nations Children's Fund  RSYR19-MS-157616-1
9                           Lebanon Humanitarian Fund                 NaN
10      United Nations High Commissioner for Refugees  RSYR19-MS-157634-1
11                          Lebanon Humanitarian Fund                 NaN
12                     United Nations Children's Fund  RSYR19-MS-157613-1
13                     United Nations Children's Fund  RSYR19-MS-157616-1
14                          Lebanon Humanitarian Fund                 NaN
15                     United Nations Children's Fund  RSYR19-MS-157615-1
16                     United Nations Children's Fund  RSYR19-MS-157615-1
17                                                NaN                 NaN
18                     United Nations Children's Fund  RSYR19-MS-157616-1
19                     United Nations Children's Fund  RSYR19-MS-157616-1
20                     United Nations Children's Fund  RSYR19-MS-157615-1
21                     United Nations Children's Fund  RSYR19-MS-157615-1
22                     United Nations Children's Fund  RSYR19-MS-157615-1
23                     United Nations Children's Fund  RSYR19-MS-157615-1
24           International Organization for Migration                 NaN
25                     United Nations Children's Fund                 NaN
26      United Nations High Commissioner for Refugees  RSYR19-MS-157633-1
27      United Nations High Commissioner for Refugees  RSYR19-MS-157633-1
28      United Nations High Commissioner for Refugees  RSYR19-MS-157634-1
29      United Nations High Commissioner for Refugees  RSYR19-MS-157634-1
30      United Nations High Commissioner for Refugees  RSYR19-MS-157634-1
31      United Nations High Commissioner for Refugees  RSYR19-MS-157633-1
32      United Nations High Commissioner for Refugees  RSYR19-MS-157634-1
33      United Nations High Commissioner for Refugees  RSYR19-MS-157634-1
34                          Lebanon Humanitarian Fund                 NaN
35  Food & Agriculture Organization of the United ...  RSYR19-MS-157493-1
36   Agency for Technical Cooperation and Development  RSYR19-MS-157448-1
37                          Lebanon Humanitarian Fund                 NaN

                                          Description Field Cluster  \
0   Lebanon : Supporting Learning and Skills Build...  Multi-sector
1   Lebanon: Education & Child Protection for Extr...  Multi-sector
2   Lebanon: Education & Child Protection for Extr...  Multi-sector
3   MENARO: Syria Crisis (Jordan and Lebanon)- No ...  Multi-sector
4   MENARO: Syria Crisis (Jordan and Lebanon) - WA...  Multi-sector
5   MENARO: Syria Crisis (Jordan and Lebanon)- WAS...  Multi-sector
6   MENARO: Syria Crisis (Jordan and Lebanon) - No...  Multi-sector
7   Providing protection to refugees living in Leb...  Multi-sector
8   Lebanon: To support the education programmes i...  Multi-sector
9                   Syria, CBPF in Lebanon [OCT 5968]           NaN
10  Assistance to vulnerable Syrian refugees and h...  Multi-sector
11                  Syria, CBPF in Lebanon [OCT 6138]           NaN
12  EGYPT: Integrated package to improve education...  Multi-sector
13  MENARO: Syria Crisis (Jordan and Lebanon) - WA...  Multi-sector
14                  Syria, CBPF in Lebanon [OCT 6370]           NaN
15  Thematic Cross Sectoral - Jordan - GARNIER (SM...  Multi-sector
16     Jordan: NLG / Makani Center Phase I (SM180556)  Multi-sector
17                                                NaN           NaN
18  Lebanon: Supporting access to formal education...  Multi-sector
19  Lebanon: Supp.the most vulnerable Lebanese and...  Multi-sector
20  Amaluna: Youth Economic Engagement - Jordan (S...  Multi-sector
21    Thematic Cross Sectoral - Jordan (SM1899100038)  Multi-sector
22    Thematic Cross Sectoral - Jordan (SM1899100038)  Multi-sector
23  Vocational training & employment opportunities...  Multi-sector
24  Border Transport, Education, Health, Livelihoo...           NaN
25  Child Protection, Education, Health, Nutrition...           NaN
26  Syrian Refugees in Jordan - Donation by miscel...  Multi-sector
27  Humanitarian Assistance for Middle East, Afric...  Multi-sector
28  Assistance to Syrian Refugees in Lebanon - Pri...  Multi-sector
29  Cash transfer program to meet the food and bas...  Multi-sector
30  2018 - Pledging Conference - Various programme...  Multi-sector
31       Amazon Smile through - UNO-Fluechtlingshilfe  Multi-sector
32                      Alghanim Industries June 2017  Multi-sector
33  Humanitarian Assistance for Middle East, Afric...  Multi-sector
34                  Syria, CBPF in Lebanon [OCT 6512]           NaN
35  The project aims to achieve improved economic ...  Multi-sector
36  Jordan ACTED Addressing urgent water, sanitati...  Multi-sector
37                  Syria, CBPF in Lebanon [OCT 6475]           NaN

    Amount (US$)     Funding status  Boundary  \
0      4232804.0  Paid Contribution  Incoming
1      4653035.0  Paid Contribution  Incoming
2      7863696.0  Paid Contribution  Incoming
3      3363229.0  Paid Contribution  Incoming
4      1494768.0  Paid Contribution  Incoming
5      1494768.0  Paid Contribution  Incoming
6      5979073.0  Paid Contribution  Incoming
7      4411765.0  Paid Contribution  Incoming
8      8426966.0  Paid Contribution  Incoming
9       500000.0  Paid Contribution  Incoming
10     2265861.0         Commitment  Incoming
11      501505.0         Commitment  Incoming
12      287637.0  Paid Contribution  Incoming
13     1537279.0  Paid Contribution  Incoming
14     1649984.0  Paid Contribution  Incoming
15      128425.0  Paid Contribution  Incoming
16     2275313.0  Paid Contribution  Incoming
17           NaN         Commitment  Incoming
18    21615472.0  Paid Contribution  Incoming
19     9840728.0  Paid Contribution  Incoming
20      287026.0  Paid Contribution  Incoming
21      142500.0  Paid Contribution  Incoming
22       47500.0  Paid Contribution  Incoming
23     2000000.0  Paid Contribution  Incoming
24     5000000.0         Commitment  Incoming
25    88800000.0         Commitment  Incoming
26      156231.0  Paid Contribution  Incoming
27     3571425.0  Paid Contribution  Incoming
28      382681.0  Paid Contribution  Incoming
29    17824074.0  Paid Contribution  Incoming
30      238949.0  Paid Contribution  Incoming
31       47609.0  Paid Contribution  Incoming
32      500000.0  Paid Contribution  Incoming
33     3571428.0  Paid Contribution  Incoming
34     1524623.0  Paid Contribution  Incoming
35      714286.0         Commitment  Incoming
36      500501.0         Commitment  Incoming
37     2275313.0  Paid Contribution  Incoming

                 Destination Country  \
0                            Lebanon
1                            Lebanon
2                            Lebanon
3                             Jordan
4                             Jordan
5                            Lebanon
6                            Lebanon
7                            Lebanon
8                            Lebanon
9                            Lebanon
10                           Lebanon
11                           Lebanon
12                             Egypt
13                           Lebanon
14                           Lebanon
15                            Jordan
16                            Jordan
17  Egypt|Iraq|Jordan|Lebanon|Turkey
18                           Lebanon
19                           Lebanon
20                            Jordan
21                            Jordan
22                            Jordan
23                            Jordan
24          Egypt|Iraq|Jordan|Turkey
25  Egypt|Iraq|Jordan|Lebanon|Turkey
26                            Jordan
27                            Jordan
28                           Lebanon
29                           Lebanon
30                           Lebanon
31                            Jordan
32                           Lebanon
33                           Lebanon
34                           Lebanon
35                            Turkey
36                            Jordan
37                           Lebanon

                              Destination emergency
0   Syrian Arab Republic - Civil Unrest (from 2012)
1   Syrian Arab Republic - Civil Unrest (from 2012)
2   Syrian Arab Republic - Civil Unrest (from 2012)
3   Syrian Arab Republic - Civil Unrest (from 2012)
4   Syrian Arab Republic - Civil Unrest (from 2012)
5   Syrian Arab Republic - Civil Unrest (from 2012)
6   Syrian Arab Republic - Civil Unrest (from 2012)
7   Syrian Arab Republic - Civil Unrest (from 2012)
8   Syrian Arab Republic - Civil Unrest (from 2012)
9   Syrian Arab Republic - Civil Unrest (from 2012)
10  Syrian Arab Republic - Civil Unrest (from 2012)
11  Syrian Arab Republic - Civil Unrest (from 2012)
12  Syrian Arab Republic - Civil Unrest (from 2012)
13  Syrian Arab Republic - Civil Unrest (from 2012)
14  Syrian Arab Republic - Civil Unrest (from 2012)
15  Syrian Arab Republic - Civil Unrest (from 2012)
16  Syrian Arab Republic - Civil Unrest (from 2012)
17  Syrian Arab Republic - Civil Unrest (from 2012)
18  Syrian Arab Republic - Civil Unrest (from 2012)
19  Syrian Arab Republic - Civil Unrest (from 2012)
20  Syrian Arab Republic - Civil Unrest (from 2012)
21  Syrian Arab Republic - Civil Unrest (from 2012)
22  Syrian Arab Republic - Civil Unrest (from 2012)
23  Syrian Arab Republic - Civil Unrest (from 2012)
24  Syrian Arab Republic - Civil Unrest (from 2012)
25  Syrian Arab Republic - Civil Unrest (from 2012)
26  Syrian Arab Republic - Civil Unrest (from 2012)
27  Syrian Arab Republic - Civil Unrest (from 2012)
28  Syrian Arab Republic - Civil Unrest (from 2012)
29  Syrian Arab Republic - Civil Unrest (from 2012)
30  Syrian Arab Republic - Civil Unrest (from 2012)
31  Syrian Arab Republic - Civil Unrest (from 2012)
32  Syrian Arab Republic - Civil Unrest (from 2012)
33  Syrian Arab Republic - Civil Unrest (from 2012)
34  Syrian Arab Republic - Civil Unrest (from 2012)
35  Syrian Arab Republic - Civil Unrest (from 2012)
36  Syrian Arab Republic - Civil Unrest (from 2012)
37  Syrian Arab Republic - Civil Unrest (from 2012)

In [46]:
political_violence = pd.read_excel("major_political_violence.xlsx")
print(political_violence)

     scode  ccode      country  year  ind  intind  intviol  intwar  civviol  \
0      AFG    700  Afghanistan  1946    1     0.0      0.0     0.0      0.0
1      AFG    700  Afghanistan  1947    1     0.0      0.0     0.0      0.0
2      AFG    700  Afghanistan  1948    1     0.0      0.0     0.0      0.0
3      AFG    700  Afghanistan  1949    1     0.0      0.0     0.0      0.0
4      AFG    700  Afghanistan  1950    1     0.0      0.0     0.0      0.0
5      AFG    700  Afghanistan  1951    1     0.0      0.0     0.0      0.0
6      AFG    700  Afghanistan  1952    1     0.0      0.0     0.0      0.0
7      AFG    700  Afghanistan  1953    1     0.0      0.0     0.0      0.0
8      AFG    700  Afghanistan  1954    1     0.0      0.0     0.0      0.0
9      AFG    700  Afghanistan  1955    1     0.0      0.0     0.0      0.0
10     AFG    700  Afghanistan  1956    1     0.0      0.0     0.0      0.0
11     AFG    700  Afghanistan  1957    1     0.0      0.0     0.0      0.0
12     AFG    700  Afghanistan  1958    1     0.0      0.0     0.0      0.0
13     AFG    700  Afghanistan  1959    1     0.0      0.0     0.0      0.0
14     AFG    700  Afghanistan  1960    1     0.0      0.0     0.0      0.0
15     AFG    700  Afghanistan  1961    1     0.0      0.0     0.0      0.0
16     AFG    700  Afghanistan  1962    1     0.0      0.0     0.0      0.0
17     AFG    700  Afghanistan  1963    1     0.0      0.0     0.0      0.0
18     AFG    700  Afghanistan  1964    1     0.0      0.0     0.0      0.0
19     AFG    700  Afghanistan  1965    1     0.0      0.0     0.0      0.0
20     AFG    700  Afghanistan  1966    1     0.0      0.0     0.0      0.0
21     AFG    700  Afghanistan  1967    1     0.0      0.0     0.0      0.0
22     AFG    700  Afghanistan  1968    1     0.0      0.0     0.0      0.0
23     AFG    700  Afghanistan  1969    1     0.0      0.0     0.0      0.0
24     AFG    700  Afghanistan  1970    1     0.0      0.0     0.0      0.0
25     AFG    700  Afghanistan  1971    1     0.0      0.0     0.0      0.0
26     AFG    700  Afghanistan  1972    1     0.0      0.0     0.0      0.0
27     AFG    700  Afghanistan  1973    1     0.0      0.0     0.0      0.0
28     AFG    700  Afghanistan  1974    1     0.0      0.0     0.0      0.0
29     AFG    700  Afghanistan  1975    1     0.0      0.0     0.0      0.0
...    ...    ...          ...   ...  ...     ...      ...     ...      ...
9862   ZIM    552     Zimbabwe  1988    1     0.0      0.0     0.0      0.0
9863   ZIM    552     Zimbabwe  1989    1     0.0      0.0     0.0      0.0
9864   ZIM    552     Zimbabwe  1990    1     0.0      0.0     0.0      0.0
9865   ZIM    552     Zimbabwe  1991    1     0.0      0.0     0.0      0.0
9866   ZIM    552     Zimbabwe  1992    1     0.0      0.0     0.0      0.0
9867   ZIM    552     Zimbabwe  1993    1     0.0      0.0     0.0      0.0
9868   ZIM    552     Zimbabwe  1994    1     0.0      0.0     0.0      0.0
9869   ZIM    552     Zimbabwe  1995    1     0.0      0.0     0.0      0.0
9870   ZIM    552     Zimbabwe  1996    1     0.0      0.0     0.0      0.0
9871   ZIM    552     Zimbabwe  1997    1     0.0      0.0     0.0      0.0
9872   ZIM    552     Zimbabwe  1998    1     0.0      0.0     0.0      0.0
9873   ZIM    552     Zimbabwe  1999    1     0.0      0.0     0.0      0.0
9874   ZIM    552     Zimbabwe  2000    1     0.0      0.0     0.0      0.0
9875   ZIM    552     Zimbabwe  2001    1     0.0      0.0     0.0      0.0
9876   ZIM    552     Zimbabwe  2002    1     0.0      0.0     0.0      0.0
9877   ZIM    552     Zimbabwe  2003    1     0.0      0.0     0.0      0.0
9878   ZIM    552     Zimbabwe  2004    1     0.0      0.0     0.0      0.0
9879   ZIM    552     Zimbabwe  2005    1     0.0      0.0     0.0      0.0
9880   ZIM    552     Zimbabwe  2006    1     0.0      0.0     0.0      0.0
9881   ZIM    552     Zimbabwe  2007    1     0.0      0.0     0.0      0.0
9882   ZIM    552     Zimbabwe  2008    1     0.0      0.0     0.0      0.0
9883   ZIM    552     Zimbabwe  2009    1     0.0      0.0     0.0      0.0
9884   ZIM    552     Zimbabwe  2010    1     0.0      0.0     0.0      0.0
9885   ZIM    552     Zimbabwe  2011    1     0.0      0.0     0.0      0.0
9886   ZIM    552     Zimbabwe  2012    1     0.0      0.0     0.0      0.0
9887   ZIM    552     Zimbabwe  2013    1     0.0      0.0     0.0      0.0
9888   ZIM    552     Zimbabwe  2014    1     0.0      0.0     0.0      0.0
9889   ZIM    552     Zimbabwe  2015    1     0.0      0.0     0.0      0.0
9890   ZIM    552     Zimbabwe  2016    1     0.0      0.0     0.0      0.0
9891   ZIM    552     Zimbabwe  2017    1     0.0      0.0     0.0      0.0

      civwar   ...    inttot  civtot  actotal  nborder  region  nregion  \
0        0.0   ...       0.0     0.0      0.0      3.0     6.0      4.0
1        0.0   ...       0.0     0.0      0.0      4.0     6.0      5.0
2        0.0   ...       0.0     0.0      0.0      4.0     6.0      7.0
3        0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
4        0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
5        0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
6        0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
7        0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
8        0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
9        0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
10       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
11       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
12       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
13       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
14       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
15       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
16       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
17       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
18       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
19       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
20       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
21       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
22       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
23       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
24       0.0   ...       0.0     0.0      0.0      4.0     6.0      9.0
25       0.0   ...       0.0     0.0      0.0      4.0     6.0     10.0
26       0.0   ...       0.0     0.0      0.0      4.0     6.0     10.0
27       0.0   ...       0.0     0.0      0.0      4.0     6.0     10.0
28       0.0   ...       0.0     0.0      0.0      4.0     6.0     10.0
29       0.0   ...       0.0     0.0      0.0      4.0     6.0     10.0
...      ...   ...       ...     ...      ...      ...     ...      ...
9862     0.0   ...       0.0     0.0      0.0      4.0     4.0     11.0
9863     0.0   ...       0.0     0.0      0.0      4.0     4.0     11.0
9864     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9865     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9866     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9867     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9868     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9869     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9870     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9871     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9872     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9873     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9874     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9875     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9876     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9877     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9878     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9879     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9880     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9881     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9882     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9883     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9884     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9885     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9886     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9887     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9888     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9889     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9890     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0
9891     0.0   ...       0.0     0.0      0.0      4.0     4.0     12.0

      afrreg  regcon  muslim  soccap
0        0.0     6.0       2       1
1        0.0     6.0       2       1
2        0.0     6.0       2       1
3        0.0     6.0       2       1
4        0.0     6.0       2       1
5        0.0     6.0       2       1
6        0.0     6.0       2       1
7        0.0     6.0       2       1
8        0.0     6.0       2       1
9        0.0     6.0       2       1
10       0.0     6.0       2       1
11       0.0     6.0       2       1
12       0.0     6.0       2       1
13       0.0     6.0       2       1
14       0.0     6.0       2       1
15       0.0     6.0       2       1
16       0.0     6.0       2       1
17       0.0     6.0       2       1
18       0.0     6.0       2       1
19       0.0     6.0       2       1
20       0.0     6.0       2       1
21       0.0     6.0       2       1
22       0.0     6.0       2       1
23       0.0     6.0       2       1
24       0.0     6.0       2       1
25       0.0     6.0       2       1
26       0.0     6.0       2       1
27       0.0     6.0       2       1
28       0.0     6.0       2       1
29       0.0     6.0       2       1
...      ...     ...     ...     ...
9862     4.0     4.0       0       3
9863     4.0     4.0       0       3
9864     4.0     4.0       0       3
9865     4.0     4.0       0       3
9866     4.0     4.0       0       3
9867     4.0     4.0       0       3
9868     4.0     4.0       0       3
9869     4.0     4.0       0       3
9870     4.0     4.0       0       3
9871     4.0     4.0       0       3
9872     4.0     4.0       0       3
9873     4.0     4.0       0       3
9874     4.0     4.0       0       3
9875     4.0     4.0       0       3
9876     4.0     4.0       0       3
9877     4.0     4.0       0       3
9878     4.0     4.0       0       3
9879     4.0     4.0       0       3
9880     4.0     4.0       0       3
9881     4.0     4.0       0       3
9882     4.0     4.0       0       3
9883     4.0     4.0       0       3
9884     4.0     4.0       0       3
9885     4.0     4.0       0       3
9886     4.0     4.0       0       3
9887     4.0     4.0       0       3
9888     4.0     4.0       0       3
9889     4.0     4.0       0       3
9890     4.0     4.0       0       3
9891     4.0     4.0       0       3

[9892 rows x 22 columns]

In [47]:
print(list(political_violence))

['scode', 'ccode', 'country', 'year', 'ind', 'intind', 'intviol', 'intwar', 'civviol', 'civwar', 'ethviol', 'ethwar', 'inttot', 'civtot', 'actotal', 'nborder', 'region', 'nregion', 'afrreg', 'regcon', 'muslim', 'soccap']

In [48]:
print(political_violence.loc[8516])

scode        SYR
ccode        652
country    Syria
year        2006
ind            1
intind         0
intviol        0
intwar         0
civviol        0
civwar         0
ethviol        0
ethwar         0
inttot         0
civtot         0
actotal        0
nborder        5
region         5
nregion       20
afrreg         0
regcon         5
muslim         2
soccap         3
Name: 8516, dtype: object

In [49]:
print(political_violence.loc[8527])

scode        SYR
ccode        652
country    Syria
year        2017
ind            1
intind         0
intviol        0
intwar         0
civviol        0
civwar         0
ethviol        0
ethwar         6
inttot         0
civtot         6
actotal        6
nborder        5
region         5
nregion       20
afrreg         0
regcon         5
muslim         2
soccap         3
Name: 8527, dtype: object